namespace Lib.Share.Enums
{
    public enum SettingNames
    {
        FontFamily,
        AppVersion,
        Language,
        Theme,
        FontSize,
        OneDriveAccessToken,
        OneDriveUserName,
        OneDriveExpiryTime,
        LastShelfId,
        MaxLastestBookCount,
        SearchEngine,
        MaxSingleColumnWidth,
        EnabledBackgroundImage,
        BackgroundImage,
        BackgroundMaskColor,
        SpeechVoice,
        IsSpeechAutoNext,
        IsAutoOpenLastBook,
        LastBookId,
        LastBackgroundSyncTime,
        DisableXboxScale,
        IsEnableAutoCheckUpdate,
        IsFirstRun
    }
}
